name: Chores

on:
  # Allows one to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the
  # "coverage-badge-action" branch and when at least one path matches a pattern
  # in the `paths` filter.
  push:
    branches:
      - coverage-badge-action
    paths:
      - .github/**
      - src/**
      - tests/**
      - package-lock.json
      - package.json
  pull_request:
    branches:
      - coverage-badge-action
    paths:
      - .github/**
      - src/**
      - tests/**
      - package-lock.json
      - package.json

env:
  NODE_VERSION: 16
  BADGE_BRANCH: gh-pages
  BADGE_PATH: storage/${{ github.ref }}/coverage-badge.svg

jobs:
  coverage-report:
    name: Fetch coverage information
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - id: npm
        name: Get npm cache directory
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
        shell: bash
      - id: cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        run: npm ci
      - id: report
        name: Report coverage
        uses: ./.github/actions/coverage-report
    outputs:
      # Assign default values to ensure `needs` context
      # is defined in dependdent job.
      total: ${{ steps.report.outputs.total }}
      threshold: ${{ steps.report.outputs.threshold }}

  coverage-handle-badge:
    name: Update coverage badge
    needs:
      - coverage-report
    if: ${{ github.ref == 'refs/heads/coverage-badge-action' && needs.coverage-report.outputs.total >= 0 }}
    continue-on-error: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # As of 2021-07-26 interpolation of environment variables for
    # an environment variable is unsupported. Must be interpolated
    # within a step, see `set-env` below.
    #
    # ```
    # env:
    #   BADGE_PATH: ${{ format(env.BADGE_PATH, github.ref }}
    # ```
    #
    # ```
    # run: |
    #   echo "BADGE_PATH=${{ format(env.BADGE_PATH, github.ref) }}" >> $GITHUB_ENV
    # ```
    #
    # ```
    # with:
    #   # path: ${{ format(env.BADGE_PATH, github.ref) }}
    # ```
    steps:
      - name: Check out action branch
        uses: actions/checkout@v2
        with:
          path: main
      - name: Check out storage branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BADGE_BRANCH }}
          path: storage
      - name: Update coverage badge
        uses: ./main/.github/actions/coverage-badge
        with:
          working-directory: storage
          coverage: ${{ needs.coverage-report.outputs.total }}
          # path: ${{ format(env.BADGE_PATH, github.ref) }}
          path: ${{ env.BADGE_PATH }}

  coverage-handle-status:
    name: Update coverage status
    needs:
      - coverage-report
    if: ${{ github.event_name == 'pull_request' && needs.coverage-report.outputs.total >= 0 }}
    continue-on-error: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Update coverage status
        uses: ./.github/actions/coverage-status
        with:
          coverage: ${{ needs.coverage-report.outputs.total }}
          threshold: ${{ needs.coverage-report.outputs.threshold }}
