name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the
  # "coverage-badge-action" branch and when at least one path matches a pattern
  # in the `paths` filter.
  push:
    branches:
      - coverage-badge-action
    paths:
      - .github/**
      - src/**
      - tests/**
      - package.json
  pull_request:
    branches:
      - coverage-badge-action
    paths:
      - .github/**
      - src/**
      - tests/**
      - package.json

  # Allows one to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Node.js v${{ matrix.node }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        node:
          # - 12
          - 14
          - 16
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node }}
            ${{ matrix.os }}-node-

      - run: npm ci
      - run: npm test
